C3-TKO/junkan

- src/components/ControlsComponent.js
- src/screen_1.html
- src/screen_2.html
- src/screen_3.html
- src/styles/Controls.scss
> Uses floating action buttons for the control buttons from now on

- src/components/ControlsComponent.js
- src/components/Main.js
- src/components/StopWatchComponent.js
- src/styles/StopWatch.scss
- test/components/StopWatchComponentTest.js
> Show time progress

- src/index.html
> Adds the roboto font via google font api

- src/components/ControlsComponent.js
- src/components/RotatorComponent.js
- src/components/ScreenLauncherComponent.js
- src/components/SlideListComponent.js
- src/styles/ScreenLauncher.scss
- test/components/ScreenLauncherComponentTest.js
Adds the possibility to jump to a specific screen by choosing one from a modal dialog that lists all available screens
> Go to screen

- package.json
- src/components/ControlsComponent.js
- src/components/IframeComponent.js
- src/components/RotatorComponent.js
> Keyboard triggers for controls

- src/components/IframeLockerComponent.js
- src/components/RotatorComponent.js
- src/styles/IframeLocker.scss
- test/components/IframeLockerComponentTest.js
> Lock iframe content

- src/components/ControlsComponent.js
> Adds the space key as trigger for stop and play

- src/components/ControlsComponent.js
- src/components/IframeLockerComponent.js
- src/components/ScreenLauncherComponent.js
- src/components/SettingsComponent.js
- src/components/SlideListEditorComponent.js
- test/components/ControlsComponentTest.js
- test/components/EditSlideFormComponentTest.js
- test/components/IframeComponentTest.js
- test/components/MainTest.js
- test/components/RotatorComponentTest.js
- test/components/ScreenLauncherComponentTest.js
- test/components/SettingsComponentTest.js
- test/components/SlideListEditorComponentTest.js
- test/components/StopWatchComponentTest.js
> Fix unit tests

- package.json
> Adds a npm script for updating the gh-pages dist

- package.json
- src/components/ExportSlidesComponent.js
- src/components/ImportSlidesComponent.js
- src/components/SlideListEditorComponent.js
- src/intl/en.js
- src/styles/ExportSlides.scss
- src/styles/ImportSlides.scss
- src/styles/SlideListEditor.scss
- test/components/ExportSlidesComponentTest.js
- test/components/ImportSlidesComponentTest.js
> Import export slides

- src/components/ReloaderComponent.js
- src/components/RotatorComponent.js
- src/components/SyncComponent.js
- src/intl/en.js
- src/styles/Reloader.scss
- test/components/ReloaderComponentTest.js
> Reload after x cycles

- src/components/Main.js
- src/index.js
Now all providers are located in the same place
closes #94
> Moves the muitheme provider to index.js

- src/components/MenuComponent.js
- src/components/ScreenLauncherComponent.js
- test/components/MainTest.js
- test/components/MenuComponentTest.js
- test/components/ProgressBarComponentTest.js
> Refactoring of the screen launcher component

- src/components/ExportSlidesComponent.js
> Aligns the form actions

- src/components/EditSlideFormComponent.js
- src/components/ImportSlidesComponent.js
- src/components/Main.js
- src/components/MenuComponent.js
- src/components/SettingsComponent.js
- src/components/SlideListEditorComponent.js
- src/components/SyncComponent.js
- test/components/EditSlideFormComponentTest.js
> Use store connect to get access to the dispatcher

- src/components/IframeComponent.js
- src/components/Main.js
- src/stores/index.js
- src/styles/Iframe.scss
- test/components/IframeComponentTest.js
I've added some CSS transitions to the Iframe.
Todos
* make transition duration configurable
* maybe use different transition styles
> add fade in/out transitions for iframe

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Empower contributions

- package.json
- src/components/IframeLockerComponent.js
- src/components/Main.js
- src/components/MenuComponent.js
- src/components/ScreenLauncherComponent.js
- src/components/SettingsComponent.js
- src/stores/index.js
- src/styles/IframeLocker.scss
- src/styles/Menu.scss
The main menu will now only be displayed if there is an interaction which triggers mouse events. Thus the main menu will remove off canvas if there is no "mouse" interaction.
Closes #122 
This is the implementation of a requested enhancement - #122 
This has been tested manually as this is not yet possible to be tested automatically until milestone https://github.com/C3-TKO/junkan/milestone/9 is completed
This projects uses [SemVer](http://semver.org/)
Regarding tests and coding styles - just relax this project has an automated tests setup. However if you want to run tests locally, than you can use ```npm run test``` from the command line. Pull requests won't be accepted if the automated travis build process failed. Should overall test coverage sink significantly the pull request won't be …
> Add menu animation and on demand display

- src/components/SlideListEditorComponent.js
- src/styles/SlideListEditor.scss
This pull requests streamlines the editing of the screen rotation list.
Closes #98 
It saves one unnecessary click in the ui
Only manually
n.a. 
This projects uses [SemVer](http://semver.org/)
Regarding tests and coding styles - just relax this project has an automated tests setup. However if you want to run tests locally, than you can use ```npm run test``` from the command line. Pull requests won't be accepted if the automated travis build process failed. Should overall test coverage sink significantly the pull request won't be accepted as well as long as you do not provide more tests ;-)
> Streamline screen rotation list editor

- src/components/IframeComponent.js
This projects uses [SemVer](http://semver.org/)
Regarding tests and coding styles - just relax this project has an automated tests setup. However if you want to run tests locally, than you can use ```npm run test``` from the command line. Pull requests won't be accepted if the automated travis build process failed. Should overall test coverage sink significantly the pull request won't be accepted as well as long as you do not provide more tests ;-)
> Catch iframe errors

- src/components/IframeComponent.js
- src/styles/App.css
- src/styles/Iframe.scss
- test/components/IframeComponentTest.js
The iframe transitions have been adjusted in order to improve performance. Switches from opacity transition to moving the old iframe off canvas
Closes #87 
This feature improves the performance of the transition as this application will most likely be hosted on machines with a cost efficient minimal powered cpus.
Manually tested as mounted rendering is not yet supported within this project
n.a.
> Iframe transitions

- src/actions/addSlide.js
- src/actions/deleteSlide.js
- src/actions/editSettings.js
- src/actions/editSlide.js
- src/actions/updateSyncState.js
- src/constants/ActionTypes.js
- src/reducers/settings.js
- src/reducers/slides.js
- src/reducers/syncState.js
- src/stores/index.js
Technical refatoring
Technical refactoring
Closes #133 
See related issue #133 
Tested manually by invoking all actions
n.a.
> Action types constants

- test/reducers/settingsTest.js
- test/reducers/slidesTest.js
- test/reducers/syncStateTest.js
Adds the specification for the slides reducer
Adds unit tests a.k.a. specifications to raise the code coverage for tests to 100%
Closes #76 
Increase code coverage and therefore raise maintainability
n.a.
> Slides reducer coverage 100

- package.json
- src/components/EditSlideFormComponent.js
- src/components/ImportSlidesComponent.js
- src/components/SettingsComponent.js
- src/components/SlideListEditorComponent.js
- src/index.js
- src/stores/index.js
- test/components/EditSlideFormComponentTest.js
- test/components/ExportSlidesComponentTest.js
- test/components/IframeComponentTest.js
- test/components/IframeLockerComponentTest.js
- test/components/ImportSlidesComponentTest.js
- test/components/ReloaderComponentTest.js
- test/components/ScreenLauncherComponentTest.js
- test/components/SettingsComponentTest.js
- test/components/SlideListEditorComponentTest.js
- test/components/SyncComponentTest.js
- test/helpers/intl-enzyme-test-helper.js
- test/reducers/syncStateTest.js
Switches to enzyme as react test framework
- Utilizes enzyme for shallow rendering or mounting test components  
- Adds a helper for handling react-intl injecting
- Adds a very basic render test scenario for all existing components
Closes #66 
- This pull request reenables the basic component rendering unit tests
- This pull request will raise the code coverage 
Yes - it adds tests or reactivates them again
n.a.
> Use enzyme for component tests

- src/components/ImportSlidesComponent.js
See issue #132 
Closes #132 
Bugfix
Manually, as there is not yet a solution established for testing
n.a.
> Aligns the name for open/close handlers
